export const data = [
    {
        title: "Popular on Netflix",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/tv/popular?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_networks=213`,
        home: true,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "Movies Popular on Netflix",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/movie/popular?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_networks=213`,
        home: false,
        tv: false,
        movie: true,
        isNew: false,
    },
    {
        title: "Trending this Day",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/trending/all/day?api_key=${process.env.REACT_APP_MOVIES_API_KEY}`,
        home: true,
        tv: false,
        movie: false,
        isNew: true,
    },
    {
        title: "TV Shows Trending this Day",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/trending/tv/day?api_key=${process.env.REACT_APP_MOVIES_API_KEY}`,
        home: false,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "Trending this Week",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/trending/all/week?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_networks=213`,
        home: true,
        tv: false,
        movie: false,
        isNew: true,
    },
    {
        title: "TV Shows Trending this Week",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/trending/tv/week?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_networks=213`,
        home: false,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "Movie Trending this Week",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/trending/movie/week?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_networks=213`,
        home: false,
        tv: false,
        movie: true,
        isNew: false,
    },
    {
        title: "English Movies",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/movie?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_original_language=en`,
        home: true,
        tv: false,
        movie: true,
        isNew: false,
    },
    {
        title: "US TV Shows",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_original_language=en&page=region=US`,
        home: true,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "Anime",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&language=en-US&page=1&with_genres=16&with_keywords=210024|287501&with_text_query=death`,
        home: true,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "K-Drama",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&sort_by=popularity.desc&with_genres=18&with_original_language=ko`,
        home: true,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "Korean Movies",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/movie?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&sort_by=popularity.desc&with_genres=18&with_original_language=ko`,
        home: true,
        tv: false,
        movie: true,
        isNew: false,
    },
    {
        title: "Top Movies in India Today",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/movie?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_original_language=hi`,
        home: true,
        tv: false,
        movie: true,
        isNew: true,
    },
    {
        title: "TV Sci-Fy and Fantasy",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_genres=10765`,
        home: true,
        tv: true,
        movie: false,
        isNew: false,
    },
    {
        title: "Movie New Releases",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/movie/latest?api_key=${process.env.REACT_APP_MOVIES_API_KEY}`,
        home: true,
        tv: false,
        movie: true,
        isNew: false,
    },
    {
        title: "TV New Releases",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/tv/latest?api_key=${process.env.REACT_APP_MOVIES_API_KEY}`,
        home: true,
        tv: true,
    },
    {
        title: "Top 10 TV Shows in India Today",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_original_language=hi`,
        home: true,
        tv: true,
        isNew: true,
    },
    {
        title: "Japanese Action Anime",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&page=1&with_genres=16,10759&with_keywords=210024|287501&with_text_query=death&with_original_language=ja`,
        home: true,
        tv: true,
    },
    {
        title: "TV Action and Adventure",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&page=1&with_genres=10759`,
        home: true,
        tv: true,
    },
    {
        title: "US Action",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/movie?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_genres=28&with_original_language=en&page=region=US`,
        home: true,
        movie: true,
    },
    {
        title: "Movie Thrillers",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/movie?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_genres=53&with_original_language=en&page=region=US`,
        home: true,
        movie: true,
    },
    {
        title: "TV Only on Netflix",
        url: `${process.env.REACT_APP_MOVIES_BASE_URL}/discover/tv?api_key=${process.env.REACT_APP_MOVIES_API_KEY}&with_networks=213`,
        home: true,
        tv: true,
    },
];
